### ISSUE TITLE
Deriving Connection Weights

### ISSUE THREAD

**Issue by parkbanks** [ericstrobl/CCI#1]
Hi there, I've been reading through the CCI package. I've been testing it on some groundwater chemistry data-sets and it works really well. Is there a method to derive weights of each edge, given a derived MAAG?

**Comment by ericstrobl** [comment]
Hey, unfortunately no one knows how to derive the weights yet without making additional assumptions. This is still an active area of research. The MAAG helps us identify what the causes are, but we havent figured out how to identify the causal strengths (or Pr[Y|do(X)] more generally)

**Comment by parkbanks** [comment]
Thank you for letting me know! I'll look more into the literature then.
